Kubewarden 0.1.0

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -12,19 +12,23 @@ NORMAL="\033[22m"
 SINGLE_VERSION="false" # Should we publish all plugins using the version from-the top-level package file?
 PUSH=""
 REGISTRY=""
-REG=""
+REGISTRY_ORG=""
+IMAGE_PREFIX="ui-extension-"
+FORCE="false"
+GITHUB_BUILD="false"
 
 usage() {
   echo "Usage: $0 [-v] [plugins]"
   #echo "  -v        Publish plugins using the version from-the top-level package file"
-  echo "  -p        Push container images on build"
-  echo "  -r <name> Specify destination container registry for built images"
-  echo ""
-  echo ""
+  echo "  -p          Push container images on build"
+  echo "  -f          Force building the chart even if it already exists"
+  echo "  -r <name>   Specify destination container registry for built images"
+  echo "  -o <name>   Specify destination container registry organization for built images"
+  echo "  -i <prefix> Specify prefix for the built container image (default: 'ui-extension-')"
   exit 1
 }
 
-while getopts "hvr:p" opt; do
+while getopts "hvr:o:pi:fg" opt; do
   case $opt in
     h)
       usage
@@ -36,11 +40,21 @@ while getopts "hvr:p" opt; do
       PUSH="--push"
       ;;
     r)
-      REG="${OPTARG}"
-      REGISTRY="${REG}/"
+      REGISTRY="${OPTARG%/}/"
       ;;
-    *)
-      usage
+    o)
+      REGISTRY_ORG="${OPTARG}"
+      ;;
+    i)
+      IMAGE_PREFIX="${OPTARG}"
+      ;;
+    f)
+      FORCE="true"
+      ;;      
+    g)
+      GITHUB_BUILD="true"
+    ;;      *)
+    usage
       ;;
   esac
 done
@@ -54,12 +68,19 @@ echo -e "${CYAN}${BOLD}Publishing UI Plugins${RESET}"
 
 pushd ${BASE_DIR} > /dev/null
 
-VERSION=$(jq -r .version package.json)
-echo "Version: $VERSION"
+# VERSION=$(jq -r .version package.json)
+# echo "Version: $VERSION"
+
+echo "Image prefix: ${IMAGE_PREFIX}"
 
 # --------------------------------------------------------------------------------
 # Check that we have the required commands avaialble for this script
 # --------------------------------------------------------------------------------
+
+if ! [[ -d ${BASE_DIR}/node_modules ]]; then
+  echo -e "${YELLOW}You must run ${BOLD}yarn install${NORMAL} before running this script${RESET}"
+  exit 1
+fi
 
 COMMANDS=("node" "jq" "yq" "git" "docker" "helm" "yarn")
 HAVE_COMMANDS="true"
@@ -77,9 +98,18 @@ fi
 
 # --------------------------------------------------------------------------------
 
-REPO=$(git config --get remote.origin.url | sed -e 's/^git@.*:\([[:graph:]]*\).git/\1/')
 
-echo "GitHub Repository: ${REPO}"
+if [[ -z ${REGISTRY_ORG} ]]; then
+  # Infer that the user has the same Docker registry org as their GitHub org
+  GITHUB_REPO=$(git config --get remote.origin.url | sed -e 's/^git@.*:\([[:graph:]]*\).git/\1/')
+  REGISTRY_ORG=$(dirname ${GITHUB_REPO})
+  echo -e "Inferring built images will reside in registry organization ${CYAN}${BOLD}${REGISTRY}${REGISTRY_ORG}${RESET} based on configured origin remote pointing to ${CYAN}${BOLD}${GITHUB_REPO}${RESET}"
+fi
+if [[ -z ${REGISTRY_ORG} ]]; then
+  # Inferring from the git config still failed
+  echo "Cannot build images without valid organization for Docker images. Unable to infer REGISTRY_ORG="
+  exit 1
+fi
 
 docker images > /dev/null
 if [ $? -ne 0 ]; then
@@ -95,16 +125,19 @@ mkdir -p ${CHARTS}
 TMP=${BASE_DIR}/tmp
 CHART_TMP=${BASE_DIR}/tmp/_charts
 rm -rf ${TMP}
+mkdir -p ${TMP}
 
 CHART_TEMPLATE=${BASE_DIR}/tmp/ui-plugin-server
 
 # --------------------------------------------------------------------------------
 # Clone the plugin server template into the temporary folder
 # --------------------------------------------------------------------------------
-git clone -q https://github.com/rancher/ui-plugin-server.git ${CHART_TEMPLATE}
+pushd ${TMP} > /dev/null
+git clone -q https://github.com/nwmac/ui-plugin-server.git
+popd > /dev/null
 
 # --------------------------------------------------------------------------------
-# Iterate through all packages - build them all or build only those specified on the command line
+# Iterate through all packages - built them all or build only those specified on the command line
 # --------------------------------------------------------------------------------
 for d in pkg/*/ ; do
   pkg=$(basename $d)
@@ -116,11 +149,6 @@ for d in pkg/*/ ; do
     PKG_ASSET=${ASSETS}/${pkg}/${PKG_NAME}.tgz
 
     echo -e "${CYAN}${BOLD}Building plugin: ${pkg} (${PKG_VERSION}) ${RESET}"
-
-    if [ -f ${PKG_ASSET} ]; then
-      echo -e "${YELLOW}Plugin has already been published - skipping${RESET}"
-      continue;
-    fi
 
     echo "Package version: ${PKG_VERSION}"
     echo "Package folder:  ${PKG_NAME}"
@@ -135,26 +163,56 @@ for d in pkg/*/ ; do
     # Create the container image
     # --------------------------------------------------------------------------------
     mkdir -p ${TMP}/container
-    cp -R ${CHART_TEMPLATE}/ ${TMP}/container
+    cp -R ${CHART_TEMPLATE}/* ${TMP}/container/    
 
     # Copy the plugin assets
     rm -rf ${TMP}/container/plugin
     mkdir ${TMP}/container/plugin
 
-    cp -R ${BASE_DIR}/dist-pkg/${PKG_NAME}/ ${TMP}/container/plugin
+    cp -R ${BASE_DIR}/dist-pkg/${PKG_NAME}/* ${TMP}/container/plugin
     rm -f ${TMP}/container/plugin/report.html
 
-    # Build the docker image
-    pushd ${TMP}/container/ui-plugin-server > /dev/null
-    echo -e "${CYAN}Building container image ...${RESET}"
-    docker build -f ./package/Dockerfile -t ${REGISTRY}${pkg}:${PKG_VERSION} .
+    if [ "${GITHUB_BUILD}" == "false" ]; then
+      # Build the docker image
+      pushd ${TMP}/container > /dev/null
+      echo -e "${CYAN}Building container image ...${RESET}"
 
-    if [ "${PUSH}" == "--push" ]; then
-      echo -e "${CYAN}Pusing container image ...${RESET}"
-      docker push ${REGISTRY}${pkg}:${PKG_VERSION}
+      REGISTRY=${REGISTRY} ORG=${REGISTRY_ORG} REPO=${IMAGE_PREFIX}${pkg} TAG=${PKG_VERSION} ./scripts/package
+
+      if [ "${PUSH}" == "--push" ]; then
+        echo -e "${CYAN}Pushing container image ...${RESET}"
+
+        # Ensure that you do not overwrite production images
+        if [[ "${REGISTRY_ORG}" == "rancher" ]]; then
+          IMAGE=${REGISTRY}${REGISTRY_ORG}/${IMAGE_PREFIX}${pkg}:${PKG_VERSION}
+          if docker manifest inspect 2>&1 1>/dev/null; then
+            echo -e "${RED}Cannot overwrite production image ${IMAGE} since it already exists${RESET}"
+            exit 1
+          fi
+        fi
+
+        docker push ${REGISTRY}${REGISTRY_ORG}/${IMAGE_PREFIX}${pkg}:${PKG_VERSION}
+      fi
+
+      popd > /dev/null
+    else
+      echo -e "${CYAN}Adding plugin code ...${RESET}"
+
+      EXT_FOLDER=${BASE_DIR}/extensions/${pkg}/${PKG_VERSION}
+      PKG_DIST="${BASE_DIR}/dist-pkg/${PKG_NAME}"
+
+      rm -rf ${EXT_FOLDER}
+
+      mkdir -p ${EXT_FOLDER}/plugin
+
+      # Copy the code into the folder
+      cp -R ${PKG_DIST}/* ${EXT_FOLDER}/plugin
+
+      pushd ${BASE_DIR}/extensions/${pkg}/${PKG_VERSION} > /dev/null
+      rm -f plugin/report.html
+      find plugin -type f | sort > files.txt
+      popd > /dev/null
     fi
-
-    popd > /dev/null
 
     rm -rf ${TMP}/container
 
@@ -162,38 +220,46 @@ for d in pkg/*/ ; do
     # Create the Helm chart
     # --------------------------------------------------------------------------------
 
+    if [ -f ${PKG_ASSET} ] && [ "${FORCE}" == "false" ]; then
+      echo -e "${YELLOW}Helm chart has already been created - skipping${RESET}"
+      continue;
+    fi
+
     CHART_FOLDER=${CHARTS}/${pkg}/${PKG_VERSION}
 
     mkdir -p ${ASSETS}/${pkg}
     rm -rf ${CHART_FOLDER}
     mkdir -p ${CHART_FOLDER}
 
-    cp -R ${CHART_TEMPLATE}/charts/* ${CHART_FOLDER}
+    cp -R ${CHART_TEMPLATE}/charts/ui-plugin-server/* ${CHART_FOLDER}
 
     # Update Chart.yaml and values.yaml from the package file metadata
-    # Use the script from the template repository, if it is there
+    # Use the script from the template repository
+    echo -e "${CYAN}Patching Helm chart template${RESET}"
 
-    # ${SCRIPT_DIR}/patch ${CHART_FOLDER} ${BASE_DIR}/pkg/${pkg}/package.json "${REG}"    
-
-    # if [ -f ${SCRIPT_DIR}/patch ]; then
-    #   echo "Patching Helm chart template using local script"
-    #   cat ${BASE_DIR}/pkg/${pkg}/package.json
-    #   ${SCRIPT_DIR}/patch ${CHART_FOLDER} ${BASE_DIR}/pkg/${pkg}/package.json "${REG}"
-    # else if [ -f ${CHART_TEMPLATE}/scripts/patch ]; then
-    #   echo "Patching Helm chart template"
-    #   cat ${BASE_DIR}/pkg/${pkg}/package.json
-    #   ${CHART_TEMPLATE}/scripts/patch ${CHART_FOLDER} ${BASE_DIR}/pkg/${pkg}/package.json "${REG}"
-    # else
-    #   # Remove this fallback once the patch script is working
-    #   ${SCRIPT_DIR}/helmgen ./pkg/${pkg} ${CHART_FOLDER}
-    # fi
-
-    ${SCRIPT_DIR}/helmgen ${CHART_FOLDER} ./pkg/${pkg}/package.json "${REG}"
+    CHART=${CHART_FOLDER} REGISTRY="${REGISTRY}" ORG="${REGISTRY_ORG}" PACKAGE_JSON=${BASE_DIR}/pkg/${pkg}/package.json ${CHART_TEMPLATE}/scripts/patch
 
     # Copy README file from the plugin to the Helm chart, if there is one
     if [ -f "./pkg/${pkg}/README.md" ]; then
       cp ./pkg/${pkg}/README.md ${CHART_FOLDER}/README.md
     fi
+
+    if [ "${GITHUB_BUILD}" == "true" ]; then
+      echo "Patching for GitHub build"
+      pushd ${CHART_FOLDER} > /dev/null
+      ls -al
+      cd templates
+      mv cr.yaml temp.cr
+      rm *.yaml
+      mv temp.cr cr.yaml
+      ENDPOINT=https://raw.githubusercontent.com/nwmac/ui-kubewarden-ui/main/extensions/${pkg}/${PKG_VERSION}
+      sed -i.bak -e 's@endpoint: .*@endpoint: '"${ENDPOINT}"'@g' cr.yaml       
+      rm *.bak
+      popd > /dev/null
+    fi
+
+    # Additional patches
+    ${SCRIPT_DIR}/helmpatch ${CHART_FOLDER} "${BASE_DIR}/pkg/${pkg}/package.json" "${REGISTRY}${REGISTRY_ORG}/${IMAGE_PREFIX}${pkg}"
 
     # Package into a .tgz helm chart
     helm package ${CHART_FOLDER} -d ${ASSETS}/${pkg}
@@ -208,7 +274,7 @@ for d in pkg/*/ ; do
     fi
 
     # Base URL referencing assets directly from GitHub
-    BASE_URL="https://raw.githubusercontent.com/${REPO}/main/assets/${pkg}"
+    BASE_URL="assets/${pkg}"
 
     rm -rf ${CHART_TMP}
     mkdir -p ${CHART_TMP}
@@ -221,18 +287,6 @@ for d in pkg/*/ ; do
     BUILT="true"
   fi
 done
-
-
-echo -e "${CYAN}Creating GitHub Release${RESET}"
-
-# Create release and upload Helm charts to the GitHub release
-gh release create -R ${REPO} ${VERSION} --generate-notes -t "Release ${VERSION}" ${CHART_TMP}/*.tgz
-gh release upload -R ${REPO} ${VERSION} ${CHART_TMP}/*.tgz
-
-#cat index.yaml
-git add index.yaml
-git commit -m "Update Helm repository index for version ${VERSION}"
-git push origin HEAD:gh-pages -f
 
 if [ "${BUILT}" == "true" ]; then
   echo "One or more packages built"
